### ISSUE TITLE
Installation failed on Microsoft R Server

### ISSUE THREAD

**Issue by kevinbsc** [ropensci/tokenizers#28]
* installing *source* package ‘tokenizers’ ...
** package ‘tokenizers’ successfully unpacked and MD5 sums checked
** libs
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/home/bchae/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'RcppExports.o' failed
make: [RcppExports.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/home/bchae/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"      -c shingle_ngrams.cpp -o shingle_ngrams.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'shingle_ngrams.o' failed
make: [shingle_ngrams.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG  -DU_STATIC_IMPLEMENTATION -I"/home/bchae/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"      -c skip_ngrams.cpp -o skip_ngrams.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'skip_ngrams.o' failed
make: [skip_ngrams.o] Error 127 (ignored)
-shared -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -o tokenizers.so RcppExports.o shingle_ngrams.o skip_ngrams.o -L/usr/lib64/microsoft-r/3.3/lib64/R/lib -lR
sh: line 2: -shared: command not found
/usr/lib64/microsoft-r/3.3/lib64/R/share/make/shlib.mk:6: recipe for target 'tokenizers.so' failed
make: *** [tokenizers.so] Error 127
ERROR: compilation failed for package ‘tokenizers’

**Comment by lmullen** [comment]
It is not possible for me to offer support for a proprietary platform. Are you able to compile any packages on Microsoft R Server? If you can submit a bug report using just Microsoft R Open I'll see if I can figure out why it is not compiling.

**Comment by joshts0** [comment]
I work for Microsoft on Microsoft R Open/server.

This is not actually an MRO issue directly, this issue comes from upstream R:

https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17189

You can see here...
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -DU_STATIC_IMPLEMENTATION -I"/home/bchae/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -c RcppExports.cpp -o RcppExports.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory

As if it is trying to run gcc/g++ ... but skipping the gcc/g++ command.

You need to modify the Makeconf for MRO...
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf 

You will see... (this may depend on the system and Linux distro you are running it on...). But the point is, CXX1X are blank.

CXX = g++
CXXCPP = $(CXX) -E
CXXFLAGS = -DU_STATIC_IMPLEMENTATIN -O2 -g $(LTO)
CXXPICFLAGS = -fpic
CXX1X =
CXX1XFLAGS =
CXX1XPICFLAGS =
CXX1XSTD =  


You could change it to something like...

CXX = g++
CXXCPP = $(CXX) -E
CXXFLAGS = -DU_STATIC_IMPLEMENTATIN -O2 -g $(LTO)
CXXPICFLAGS = -fpic
CXX1X=g++
CXX1XFLAGS = -DU_STATIC_IMPLEMENTATIN -O2 -g $(LTO)
CXX1XPICFLAGS = -fpic
CXX1XSTD = --std=c++0x


This should help resolve _that_ error. We (I work at Microsoft for Microsoft R support) are aware of this issue and it should be addressed in a later release.  

I suspect you may be running on Redhat though... if that is the case, you may run into another problem once you have resolved that. I will outline this just in case...

If you are using RHEL6... RHEL6 comes with gcc 4.4.x, but from what I found on here, tokenizers requires at least 4.7. This is not available for RHEL6 out of the box, so you will need to use the Developer Toolset.. 
https://access.redhat.com/solutions/19458

Installation instructions are here:
https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/6/html/6.0_Release_Notes/System_Requirements.html#Installation_upgrading

According to the tokenizer folk, you need at least 4.7. I tested only on 4.7... I didn't test higher than that. 

If you are using CentOS, you won't have access to Redhats Developer Toolset. There is a CentOS equivalent (there are a few actually that will work...). This is not necessarily the only one you can use, but this worked for me:

As root (or, use sudo):
#This will download the repo file for a devtools repo
wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo -O /etc/yum.repos.d/devtools-1.1.repo

#You need to install devtoolset-1.1 (again, there are others, and newer, that may work). This will install new packages _along side_ your already existing gcc 4.4.
yum install devtoolset-1.1

Then you need to modify this...
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf 


Because the devtoolset installs their version of g++ to /opt/centos/devtoolset-1.1, so you need to tell MRO to use this version of g++.

Something like this...  (note: if you are using RHEL, and not CentOS, you will need to use the appropriate path to g++ from the Developer Toolset)
CXX=/opt/centos/devtoolset-1.1/root/usr/bin/g++
CXXCPP = $(CXX) -E
CXXFLAGS = -DU_STATIC_IMPLEMENTATIN -O2 -g $(LTO)
CXXPICFLAGS = -fpic
CXX1X=/opt/centos/devtoolset-1.1/root/usr/bin/g++
CXX1XFLAGS = -DU_STATIC_IMPLEMENTATIN -O2 -g $(LTO)
CXX1XPICFLAGS = -fpic
CXX1XSTD = --std=c++11

Note this line:
 CXX1XSTD = --std=c++11

This is important - this is the reason you have to use gcc 4.7+, because before this, the C++11 support (previously referred to as c++0x) was not there enough for tokenizer to compile.

Now, you should be able to compile tokenizer.

After you have done that, it is up to you if you want to revert the changes back to use the older g++. I wouldn't foresee any issues with compiling any other packages, as it should be backwards compatible, but if you have any, you know where to look.

**Comment by lmullen** [comment]
Thanks for the help, @joshts0.
